export enum Link {
  NOT_APPLY,
  FIRST_FILTRATION,
  DEPARTMENT_FILTRATION,
  INTERVIEW,
  OFFER_COMMUNICATION,
  WAIT_FOR_HIRED,
}

export enum Status {
  WAIT_FOR_HR_FILTERED,
  WAIT_FOR_DEPARTMENT_FILTERED,
  WAIT_FOR_ARRANGE_INTERVIEW,
  INVITED,
  TIME_NOT_RIGHT,
  BE_REJECTED,
  WAIT_FOR_INTERVIEW,
  WAIT_FOR_OFFER_COMMUNICATION,
  WAIT_FOR_HIRED,
  OBSOLETE,
}

export enum CandidateOperation {
  AGREE,
  CHANGE_THE_TIME,
  REJECT,
}