export enum Link {
  NOT_APPLY,
  FIRST_FILTRATION,
  DEPARTMENT_FILTRATION,
  INTERVIEW,
  OFFER_COMMUNICATION,
  WAIT_FOR_HIRED,
  HIRED,
}

export enum Status {
  WAIT_FOR_APPLY,
  WAIT_FOR_HR_FILTERED,
  WAIT_FOR_DEPARTMENT_FILTERED,
  WAIT_FOR_ARRANGE_INTERVIEW,
  INVITED,
  TIME_NOT_RIGHT,
  WAIT_FOR_INTERVIEW,
  WAIT_FOR_OFFER_COMMUNICATION,
  WAIT_FOR_HIRED,
  HIRED,
  BE_REJECTED,
  OBSOLETE,
}

export enum Operations {
  PASS,
  OBSOLETE,
  ARRANGE,
  RESCHEDULE,
  FINISH,
  AGREE,
  REQUEST_RESCHEDULING,
  REJECT,
}

export enum Education {
  DOCTOR,
  MASTER,
  UNDERGRADUATE,
  JUNIOR_COLLEGE,
  HIGH_SCHOOL,
  OTHER,
}
